config/routes.rb
Rails.application.routes.draw do
#static_pages
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/bonus'
#Events
get 'events/:id/participe/', to: 'events#participe'
get 'events/:id/unfollow', to: 'events#unfollow'
get '/new-event', to: 'events#new'
post '/new-event', to: 'events#create'
get '/all-events', to: 'events#index'
resources :events
#Sessions
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
#Users
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_and_belongs_to_many :attendees, class_name: "User"

  validates :title, presence: true
  validates :description, presence: true
  validates :date, presence: true
  validates :place, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, class_name: "Event"
  has_and_belongs_to_many :attended_events, class_name: "Event"
  has_secure_password
  #VALIDATIONS COMMENTEES POUR FACILITER LES TESTS

  # before_save { self.email = email.downcase }

  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :email, presence: true, length: { maximum: 255 },
                    # format: { with: VALID_EMAIL_REGEX },
                    # uniqueness: { case_sensitive: false }
  # validates :name, presence: true, length: { minimum: 3, maximum: 20 }

  # validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
      @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.creator = current_user

    if @event.save
      flash[:success] = "Event créé avec succès ! "
       redirect_to @event
    else
      flash.now[:danger] = "Veuillez complèter tous les champs"
       render 'new'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def edit
    @event = Event.find(params[:id])
  end

  def index
    @events = Event.all
  end

  def participe
    @event = Event.find(params[:id])
    if
      @event.attendees.include? current_user
      flash[:warning] = "Vous êtes déjà inscrit"
      redirect_to @event
    else
      @event.attendees << current_user
      flash[:success] = "Félicitation, vous êtes inscrit à l'événement !"
      redirect_to @event
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def unfollow
    @event = Event.find(params[:id])
    @event.attendees.delete(current_user)
    redirect_to current_user
    flash[:warning] = "Vous ne suivez plus cet évenement."

  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Event mis à jour"
      redirect_to @event
    else
      render 'edit'
    end
  end


  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :place)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new

  end

  def create
    user = User.find_by(email: params[:session][:email])
      if user && user.authenticate(params[:session][:password])
        log_in(user)
        flash[:success] = "Bienvenue sur EventBrite"
        redirect_to user
      else
        flash.now[:danger] = "Mauvaise combinaison email/password"
        render 'new'
      end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      flash[:success] = "Connexion avec succès le #{Date.today}"

      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profil mis à jour"
      redirect_to @user
    else
      render 'edit'
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
     session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
   !current_user.nil?
  end

  def log_out
   session.delete(:user_id)
   @current_user = nil
   flash[:success] = "Good bye"
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<div class="container">
  <h1>Modifier mon Event</h1>

  <div class="col-md-6 col-md-offset-3">
    <%= form_for(current_user) do |f| %>

      <p>
        <h3>Titre:</h3>
        <%= f.text_field :title, class: 'form-control' %>
      </p>
    </br>
      <p>
        <h3>Description:</h3>
        <%= f.text_area :description, class: 'form-control' %>
      </p>
    </br>
      <p>
        <h3>Date:</h3>
        <%= f.date_field :date, class: 'form-control' %>
      </p>
    </br>
      <p>
        <h3>Lieu:</h3>
        <%= f.text_field :place, class: 'form-control' %>
      </p>
    </br>
    </br>
        <%= f.submit "Modifier votre event", class: "btn btn-success" %>
        <%= link_to("Supprimer l'Event", event_path, method: :delete, class: "btn btn-danger") %>

    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<strong><h2>Tous les Events</h2></strong>

<table class="table table-hover">
  <tr>
    <th>Titre:</th>
    <th>Description:</th>
    <th>Date:</th>
    <th>Lieu:</th>
    <% if logged_in? %>
      <th>créé par:</th>
      <th>Action:</th>
      <th>Participants:</th>
    <%end%>
  </tr>

  <%@events.each do |event|%>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.description %></td>
      <td><%= event.date %></td>
      <td><%= event.place %></td>
      <% if logged_in? %>
        <td><%=link_to(event.creator.name, user_path(event.creator.id))%></td>
        <td><%=link_to("Voir", event_path(event.id))%></td>
        <td><%=link_to(event.attendees.size, event_path(event.creator.id))%></td>
      <% end %>
    </tr>
  <%end%>
</table>

app/views/events/new.html.erb
<div class="container">
  <h1>Céez votre Event</h1>
</br>
</br>
</br>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@event) do |f| %>
          <h3>Nom de l'Event:</h3><%= f.text_field :title%>
          <h3>Description:</h3><%= f.text_area :description %>
          <h3>Date:</h3><%= f.date_field :date %>
          <h3>Lieu:</h3><%= f.text_field :place %>
          </br>
          </br>
          <%= f.submit "Créer mon Event", class: "btn btn-success" %>
          <% end %>

        </div>
      </div>
</div>

app/views/events/show.html.erb
<div class="container">

    <section class="user_info">
      <h1><%= @event.title %></h1>

      <div class="Event-creator">
        <h4>Event créé par <%= link_to(@event.creator.name.capitalize, user_path(@event.creator.id))%></h4>
      </div>

    </section>
    </br>
    </br>
    </br>
    <div class="event_description">
      <h2><%= @event.description %></h2>
    </div>

    <h3>L'Event aura lieu à <%= @event.place %></h3>
    <h3> Le <%= @event.date %> </h3>

    </br>

    <%  if @event.creator.id == current_user.id %>
      <%= link_to "Modifier", edit_event_path, class: "btn btn-primary" %>
      <%= link_to "Supprimer", event_path, method: :delete, class: "btn btn-danger" %>
    <%end%>
    <% if @event.attendees.include? current_user %>
      <%= link_to "Ne plus participer", { :controller => "events", :action => "unfollow"}, class: "btn btn-danger" %>
    <% else %>
      <%= link_to "Participer", { :controller => "events", :action => "participe"}, class: "btn btn-success" %>
    <% end %>
    </br>

    <h2>Liste des participants à l'Event</h2>

    <table class="table table-hover">
      <tr>
        <th>Nom des Participants:</th>
        <th>email:</th>
        <th>Profil:</th>
      </tr>

      <%@event.attendees.each do |attendee|%>
        <tr>
          <td><%= attendee.name %></td>
          <td><%= attendee.email %></td>
          <td> <%= link_to('Voir le profil', user_path(attendee)) %> </td>
        </tr>
      <%end%>
    </table>
  </br>
  </br>
    <div class="Retour_index">
      <%= link_to("Retour aux Events", events_path, class: "btn btn-primary" )%>
    </div>
</div>

app/views/events/showattendees.html.erb
<h1>Liste des participants à l'Event</h1>
<h2>event.name</h2>

<table class="table table-hover">
  <tr>
    <th>Nom</th>
    <th>email</th>
  </tr>

  <%@event.attendees.each do |attendee|%>
    <tr>
      <td><%= attendee.name %></td>
      <td><%= attendee.email %></td>
    </tr>
  <%end%>
</table>

app/views/layouts/_header.html.erb
<div class="container">

  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    
    <%= link_to 'EventBriteRaf', static_pages_bonus_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation" style="">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>

        <% if logged_in? %>

          <li class="nav-item">
            <%= link_to 'Log Out', logout_path, class: 'nav-link', method: :delete %>
          <% else %>
            <%= link_to 'Log In', login_path, class: 'nav-link' %>

          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to 'Events', all_events_path, class: 'nav-link' %>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteRaf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/bonus.html.erb
<div class="container">
  <center>
      <h1>Wouhou, tu as découvert la Page Bonus!</h1>
    </br>
    </br>
    </br>
      <h3>Je te présente</h3>
        <br />
        <br />
        <br />
        <h1 class="nav-item">
          <a class="nav-link" href="https://www.facebook.com/teamwildsport/">>>>WildSport<<<</a>
        </h1>
        <br />
        <br />
        <br />
      <p>
        Ma super page facebook faites pour rassembler les sportifs!<br />
        Se motiver ensemble.<br />
        Et se retrouver sur des Events pour PARTAGER UN MOMENT DE SPORT!<br />
        C'est multi-sports, tous niveaux et sans engagements!<br />
        Alors Clique sur le Lien au dessus et rejoins nous en Likant la page!<br /><br />
        Ce weekend on fait YOGA.
      </p>
  </center>
</div>

app/views/static_pages/home.html.erb
<% if !logged_in? %>

  <div class="center jumbotron">
    <h1>Bienvenue</h1>
    </br>
    </br>
    </br>

    <h3>Je me connecte <%= link_to("Login", login_path, class: "btn btn-success" ) %></h3>

    <h3>Je m'inscris <%= link_to("SignUp", signup_path, class: "btn btn-success" ) %></h3>

    <h3>Events <%= link_to("Index", all_events_path, class: "btn btn-success" ) %></h3>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Bienvenue</h1>
    </br>
    </br>
    </br>

    <%= link_to("Consulter Profile", current_user, class: "btn btn-success" ) %></h3>
    </br>
    </br>
    <%= link_to("Céer mon Event", new_event_path, class: "btn btn-success" ) %></h3>
    </br>
    </br>
    <%= link_to("Voir tous les Events", all_events_path, class: "btn btn-success" ) %></h3>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h1>Mettre à jour mon profil</h1>

  <div class="col-md-6">
    <%= form_for(current_user) do |f| %>

      <p>
        <h3>Nom:</h3>
        <%= f.text_field :name, class: 'form-control' %>
      </p>
    </br>
      <p>
        <h3>Email:</h3>
        <%= f.text_field :email, class: 'form-control' %>
      </p>
    </br>
      <p>
        <h3>Password:</h3>
        <%= f.password_field :password, class: 'form-control' %>
      </p>
    </br>
      <p>
        <h3>Confirmation:</h3>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </p>


    </br>
    </br>

      <%= f.submit "Modifier les informations", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">

  <h1>Sign Up</h1>
  <%= form_for @user do |f| %>
    <h3>Mon Nom</h3><%= f.text_field :name %>
    <h3>Mon email</h3><%= f.text_field :email %>
    <h3>Mon Password</h3><%= f.password_field :password %>
    <h3>Confirmation</h3><%= f.password_field :password_confirmation %>
    </br>
    </br>
    <%= f.submit "Créer mon Profile", class: "btn btn-success" %>

  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">

  <h1>Mon Profile</h1>
  </br>
  </br>
  </br>
  <h2>Salut <%= @user.name.capitalize %></h2>
  <h4>Mon email:   <%= @user.email %></h4>
  </br>
  <% if @user.id == current_user.id %>
    <%= link_to("Modifier", edit_user_path, class: "btn btn-success" ) %></h3>
  </br>
  </br>
    <%= link_to("Céer mon Event", new_event_path, class: "btn btn-success" ) %></h3>

  <%end%>

</div>